# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities.builtin.provider import message 
from langbot_plugin.api.entities import events, context

class MessageEventListener(EventListener):

    async def initialize(self):
        await super().initialize()
        config = self.plugin.get_config()

        enable_prompt = config.get("prompt_add", False)
        add_prompt = config.get("prompt", "")

        if enable_prompt:
            @self.handler(events.PromptPreProcessing)
            async def handler(event_context):
                prompt = message.Message(
                            role="system",
                            content=f"You are a helpful assistant.",
                        )
                event_context.event.default_prompt.append(prompt)
                prompt = message.Message(
                            role="system",
                            content=f"This is a test.",
                        )
                event_context.event.default_prompt.append(prompt)

                if add_prompt:
                    event_context.event.default_prompt.append(add_prompt)
